// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CopyPasteWithConversion
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCopyPasteWithConversionPackageString = "ea9007e1-a0be-45cd-97b1-b33510fbc130";
        public static Guid guidCopyPasteWithConversionPackage = new Guid(guidCopyPasteWithConversionPackageString);

        public const string guidCopyPasteWithConversionPackageCmdSetString = "d1ce5fd5-aeb1-4684-b517-cb32df838c11";
        public static Guid guidCopyPasteWithConversionPackageCmdSet = new Guid(guidCopyPasteWithConversionPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int SubMenu = 0x1001;
        public const int SubMenuGroup = 0x1000;
        public const int CopyAsSeparateWordsId = 0x0100;
        public const int CopyAsCamelCase = 0x0110;
        public const int CopyAsPascalCase = 0x0120;
        public const int CopyAsSnakeCase = 0x0130;
        public const int PasteAsSeparateWordsId = 0x0200;
        public const int PasteAsCamelCase = 0x0210;
        public const int PasteAsPascalCase = 0x0220;
        public const int PasteAsSnakeCase = 0x0230;
    }
}